client:
  gemini:
    model: gemini-2.0-flash # 或者你希望使用的 Gemini 模型
    api_key: AIzaSyDgUBmKHna9XSOo4DDMJSXkTFxJLfvxiIw 
    api_type: google
    base_url: https://asia-east1-aiplatform.googleapis.com
  zhipu:
    model: GLM-4-Flash
    api_key: 398f5e33f62c6a9dc7cd95987b14aae6.rKQve5A1VUNNHW4Z
    base_url: https://open.bigmodel.cn/api/paas/v4
    price: [0.002, 0.004]
